# Generated by Django 5.2.5 on 2025-08-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Id цены"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Id продукта"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Id сессии"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("card", "Банковская карта")],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
