# Generated by Django 5.2.5 on 2025-08-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_stripe_checkout_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
